name: build and push image to harbor

on:
  push:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v3
      with:
        registry: ${{ secrets.HARBOR_URL }}
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}
